version: '3.8'

services:
  odoo18-3:
    build:
      context: .
      dockerfile: Dockerfile-18.3
      args:
        odoo_version: saas-18.3
        DISTRO: noble
        PYTHONBIN: python3.12
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    depends_on:
      - db
    volumes:
      - odoo-data:/data/odoo
      - ./extra_addons:/odoo/src/extra_addons

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  odoo-data:
  postgres-data:
